#!perl

# AUTHORITY
# DATE
# DIST
# VERSION

#use 5.010001;
use strict;
use warnings;

use Module::List::Tiny;

my $res = Module::List::Tiny::list_modules(
    'Regexp::Pattern::', {list_modules=>1, recurse=>1});
for (sort keys %$res) {
    s/\ARegexp::Pattern:://;
    print "$_\n";
}

# ABSTRACT: List all installed Regexp::Pattern::* modules
# PODNAME:

=head1 SYNOPSIS

 % list-regexp-pattern-modules


=head1 DESCRIPTION

This is a simple script to list all installed C<Regexp::Pattern::*> modules.


=head1 SEE ALSO

L<show-regexp-pattern-module>
